### ISSUE TITLE
实际生成的用户头像和用户名不是原始来源用户的

### ISSUE THREAD

**Issue by nekomeowww** [LemonNekoGH/make-it-a-quote-tg-bot#1]
## Summary

群组内 /quote 用户 A 转发的原始消息为用户 B 的消息，实际生成的用户对象是用户 A

<img width="486" alt="image" src="https://user-images.githubusercontent.com/11081491/171006110-d7310ba4-2cde-4849-a911-c59a8625433d.png">

## Expectation

应该为用户 B（实际消息来源者）生成头像和用户名

**Comment by LemonNekoGH** [comment]
已修复：8f22ac593cc2bb83d0da3dc84f2cafb4454e0421
